### ISSUE TITLE
Update to include latest icons

### ISSUE THREAD

**Issue by bobwhitelock** [1602/elm-feather#6]
Hi - I noticed some of the icons in the latest version of https://github.com/feathericons/feather are not available in `elm-feather`, e.g. `terminal`, `git-commit`, `git-merge` etc., although these can be generated using https://1602.github.io/elm-feather-icons/.

I'd update these myself but you mention that this package is semi-automatically generated, so don't want to work out what icons are missing and copy the generated code for these in if there's a better/faster automatic way. But if you give me some pointers for how to do the automatic generation I can do so. Thanks :slightly_smiling_face:

**Comment by 1602** [comment]
At some point I will automate that process, currently it is not really worth it because it happens quite rare, and involves some coding because of api change of elm-feather npm package, maybe it is not a very good idea to depend on it and better to use the same approach as https://1602.github.io/elm-feather-icons/ uses.

I will release new minor version of feather-icons shortly, see PR #7 for list of added methods.

**Comment by 1602** [comment]
@bobwhitelock thanks for nudge!
